project_name: zoltan-bot
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - image_templates:
      - ghcr.io/graytonio/zoltan-bot:latest
      - ghcr.io/graytonio/zoltan-bot:{{ .Tag }}
      - ghcr.io/graytonio/zoltan-bot:{{ .Major }}
